### ISSUE TITLE
请教：clone源码后如何运行？

### ISSUE THREAD

**Issue by byr-gdp** [lovedboy/PyTailLog#1]
看了下目录结构：
`python setup.py`
提示如下：
`usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]`
   `or: setup.py --help [cmd1 cmd2 ...]`
   `or: setup.py --help-commands`
   `or: setup.py cmd --help`

`error: no commands supplied`

进入pytaillog目录，运行server.py未果。
想学习下，小白一枚    :)

**Comment by ls0f** [comment]
Linux下面可以在终端输入：

`while true;do echo 'hello,world';sleep 1;done | python pytaillog/server.py`

然后在你浏览器输入 http://127.0.0.1:8080
